services:
  sync-server:
    build: ./server
    ports:
      - "${SERVER_IP}:3000:3000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${COMPRESSED_MEDIA_FOLDER}:/media/compressed
    environment:
      - UPLOAD_KEY=${UPLOAD_KEY}
  web-server:
    image: nginxinc/nginx-unprivileged:alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./auth:/etc/nginx/auth:ro 
      - ${COMPRESSED_MEDIA_FOLDER}:/media/compressed:ro
    networks:
      - proxy-net
      - default
    security_opt:
      - no-new-privileges:true
    depends_on:
      - sync-server
    restart: unless-stopped
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - SUBDOMAINS=${MY_SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
      - UPDATE_IP=both
      - LOG_FILE=false
      - TZ=${TZ}
    restart: unless-stopped
  p2p-tracker:
    build: 
      context: .
      dockerfile: Dockerfile.tracker
    restart: unless-stopped
#  cloudflare-tunnel: # For mobile server spin up
#    image: cloudflare/cloudflared:latest
#    command: tunnel --url http://web-server:8080
#    depends_on:
#      - web-server
#    restart: unless-stopped
#  watch-party-worker:
#    build: ./watch-party-worker
#    volumes:
#      - ${COMPRESSED_MEDIA_FOLDER}:/compressed
#      - ${UNCOMPRESSED_MEDIA_FOLDER}:/uncompressed
#    restart: unless-stopped
#    environment:
#      - UPLOAD_KEY=${UPLOAD_KEY}
#      - SERVER_IP=${SERVER_IP}
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu, video, utility]

networks:
  proxy-net:
    external: true