services:
  watch-party-worker:
    build: .
    ports:
      - "${WORKER_IP}:8081:8081"
    volumes:
      - remote_compressed:/compressed
      - ${UNCOMPRESSED_MEDIA_FOLDER}:/uncompressed
    environment:
      - UPLOAD_KEY=${UPLOAD_KEY}
      - SERVER_IP=${SERVER_IP}
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, video, utility]

volumes:
  remote_compressed:
    driver: local
    driver_opts:
      type: cifs
      o: "username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0"
      device: "//${SERVER_IP}/compressed"